name: Jekyll GitHub Pages publication

on:
  push:
    branches:
      - main

  repository_dispatch:
    types: [update_zettelkasten]
    
jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-

      # Use GitHub Deploy Action to build and deploy to Github
    - uses: jeffreytse/jekyll-deploy-action@v0.3.0
      with:
        provider: 'github'
        token: ${{ secrets.JEKYLL_SECRET  }} # It's your Personal Access Token(PAT)
        repository: ''             # Default is current repository
        branch: 'gh-pages'         # Default is gh-pages for github provider
        jekyll_src: './'           # Default is root directory
        jekyll_cfg: '_config.yml'  # Default is _config.yml
        jekyll_baseurl: ''         # Default is according to _config.yml
        bundler_ver: '>=0'         # Default is latest bundler version
        cname: ''                  # Default is to not use a cname
        actor: ''                  # Default is the GITHUB_ACTOR
        pre_build_commands: ''     # Installing additional dependencies (Arch Linux)

    - name: Alert repository_dispatch to omegakid1902.github.io repo
      uses: mvasigh/dispatch-action@main
      with:
        token: ${{ secrets.JEKYLL_GARDEN_SECRET }}
        repo: omegakid1902.github.io
        owner: omegakid1902
        event_type: publish_jekyll_garden
